# Generated by Django 3.2.3 on 2021-05-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_experience_skillsandtools'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
