# Generated by Django 3.2.3 on 2021-05-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_end_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillsAndTools',
            new_name='SkillsAndTool',
        ),
    ]
